apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  # cluster internal and non public facing but reachable by user api and tasks api
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80