apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  # ClusterIP, service that is only reachable from inside a cluster 
  type: LoadBalancer
  ports:
    - protocol: TCP
      #outside facing port
      port: 8080
      #port inside container to which request will be forwarded
      targetPort: 8080