apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: github_name/kub-demo-users:latest
        #   #pod api in same pod as user 
        # - name: auth
        #   image: github_name/kub-demo-auth:latest
          env:
            - name: AUTH_ADDRESS
              # value: "10.99.104.252"
              ## pod internal communication if auth api is also inside the same pod as user
              # value: localhost
              #
              value: "auth-service.default"